params:
    distribute: True
    ckpt_name: pangu_alpha_13B_part
    position_embedding_name: pangu_alpha_13B_position_embedding.npy
    top_query_embedding_name: pangu_alpha_13B_top_query_embedding.npy
    word_embedding_name: pangu_alpha_13B_word_embedding.npy
    ckpt_strategy_name: pangu_alpha_13B_ckpt_strategy.ckpt
    data_dev_name: dev.json
    vocab_model_name: vocab.model
    vocab_vocab_name: vocab.vocab
    ckpt_dir: ckpt_13B
    mode: 13B
    seq_length: 1024
    vocab_size: 40000
