params:
    distribute: False
    data_dev_name: dev.json
    ckpt_name: 2B6_part
    position_embedding_name: pangu_alpha_2B6_position_embedding.npy
    top_query_embedding_name: pangu_alpha_2B6_top_query_embedding.npy
    word_embedding_name: pangu_alpha_2B6_word_embedding.npy
    ckpt_strategy_name: pangu_alpha_2B6_ckpt_strategy.ckpt
    vocab_model_name: vocab.model
    vocab_vocab_name: vocab.vocab
    ckpt_dir: ckpt
    mode: 2.6B
    vocab_size: 40000