scenario:

  modelarts:
    # 计算中心region配置
    iam_endpoint: https://iam-pub.cn-central-221.ovaijisuan.com
    obs_endpoint: https://obs.cn-central-221.ovaijisuan.com
    modelarts_endpoint: https://modelarts.cn-central-221.ovaijisuan.com
    region_name: ****
    project_id: ****

    # 作业相关配置
    data_path: obs://path/dataset/AFQMC/  # input data
    output_path: obs://path/afqmc/outpath/infer/  # model output, ckpt...
    code_url: obs://path/src/afqmc/ # model scripts
    boot_file_path: obs://path/src/afqmc/main/infer_main.py
    ckpt_path: obs://path/pangu/cache/2B6/
    log_path: obs://path/pangu/afqmc/log/infer/ # log
    user_image_url: ***

    # 计算资源配置
    pool_id: ***   # 专属资源池id, 共享资源池为None
    node_num: 1
    device_num: 4   # 如果为专属池，只能填8卡。
