params:
  distribute: True
  per_batch_size: 1
  test_sample_num: 1000
  ckpt_name: 2B6_part
  position_embedding_name: pangu_alpha_2B6_position_embedding.npy
  top_query_embedding_name: pangu_alpha_2B6_top_query_embedding.npy
  word_embedding_name: pangu_alpha_2B6_word_embedding.npy
  ckpt_strategy_name: pangu_alpha_2B6_ckpt_strategy.ckpt
  data_test_name: cmrc2019_dev.json
  vocab_model_name: vocab.model
  ckpt_dir: ckpt
  mode: 2.6B